// Copyright 2024 mwask
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount } from "wagmi";
import Link from "next/link";

const Home: NextPage = () => (
	<div className={styles.container}>
    	<Head>
        	<title>StackUp x Arbitrum Forum App</title>
        	<meta
            	content="Generated by @rainbow-me/create-rainbowkit"
            	name="description"
        	/>
        	<link href="/favicon.ico" rel="icon" />
    	</Head>

    	<main className={styles.main}>
        	<h1 className={styles.title}>
            	Welcome to <span className={styles.stackup}>StackUp</span> x{" "}
            	<span className={styles.arbitrum}>Arbitrum</span> Forums
        	</h1>
        	<ConnectButton label="Sign In" />
        	<br />
        	<p className={styles.description}>
            	{useAccount().isConnected && (
                	<>
                    	You are connected. Head to our{" "}
                    	<Link className={styles.glitter} href="/forum">
                        	Forum
                    	</Link>{" "}
                    	now!
                	</>
            	)}
        	</p>
    	</main>

    	<footer className={styles.footer}>
        	<p>
            	Step into Arbitrum campaign, brought to you by{" "}
            	<a href="https://stackup.dev" target="_blank" rel="noreferrer noopener">
                	StackUp
            	</a>{" "}
            	❤️ in partnership with{" "}
            	<a href="https://arbitrum.io" rel="noreferrer noopener" target="_blank">
                	Arbitrum!
            	</a>{" "}
            	💙🧡
        	</p>
    	</footer>
	</div>
);

export default Home;